### ISSUE TITLE
Arena Numbers on Enemy Arena Frames

### ISSUE THREAD

**Issue by benjavamin** [oscargforce/TidyPlates_CleanPlates-Enhanced#1]
Hey!

I know for sure that me and **a lot** of my friends would like to have the option to turn on enemy nameplates to only show numbers instead of names above the nameplate. Would you consider adding something like this?

**Comment by oscargforce** [comment]
Sure, can do that.

**Comment by oscargforce** [comment]
Enjoy: https://github.com/oscargforce/TidyPlates_CleanPlates-Enhanced/releases/tag/v2.0.4
You can enable or disable this feature under 'Text Options' in the Interface Options menu.
